# You can add one username per supported platform and one custom link
patreon: mikekavouras
open_collective: mikekavouras
ko_fi: # Replace with your Ko-fi username
custom: # Replace with your custom donation URL
