# You can add one username per supported platform and one custom link
patreon: mikekavouras
open_collective: # Replace with your Open Collective username
ko_fi: mikekavouras
custom: https://mikekavouras.com
